import type { Metadata } from "next";
import { Tiro_Bangla } from "next/font/google";
import "./globals.css";

const tiroBangla = Tiro_Bangla({
  subsets: ["latin", "bengali"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Jade Reforestry Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${tiroBangla.className}`}>{children}</body>
    </html>
  );
}
